<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SalesMangmentSystem.BLL\SalesMangmentSystem.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SalesForms\FrmCustomer.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="SalesForms\FrmSaleOrderReport .cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="SalesForms\FrmSaleOrder.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="SalesForms\Frmproduct.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>